// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// Firebase  APPLICATION ID
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRAiXm3abwlJe9-bqkiwooBAMZlw7pLJ4',
    appId: '1:726817768219:web:56e9ff4eac1434272b49be',
    messagingSenderId: '726817768219',
    projectId: 'twitchapp-9ffca',
    authDomain: 'twitchapp-9ffca.firebaseapp.com',
    storageBucket: 'twitchapp-9ffca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQ8OJplJV0jk9hU0bx6ul9vWoEgPyEPI',
    appId: '1:726817768219:android:612d2907b6dfdd202b49be',
    messagingSenderId: '726817768219',
    projectId: 'twitchapp-9ffca',
    storageBucket: 'twitchapp-9ffca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3de7JttZFYmHFbqgV54GYOiohJ5mKY',
    appId: '1:726817768219:ios:b9e175bf04ede4652b49be',
    messagingSenderId: '726817768219',
    projectId: 'twitchapp-9ffca',
    storageBucket: 'twitchapp-9ffca.appspot.com',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3de7JttZFYmHFbqgV54GYOiohJ5mKY',
    appId: '1:726817768219:ios:4d8c5324f608c73d2b49be',
    messagingSenderId: '726817768219',
    projectId: 'twitchapp-9ffca',
    storageBucket: 'twitchapp-9ffca.appspot.com',
    iosBundleId: 'com.example.twitchClone.RunnerTests',
  );
}
